#添加服务运行参数server:server:server:
server:
  port: 8000
  servlet:
    context-path: /seckill
    session:
      timeout: 60s
  tomcat:
    max-threads: 100
    uri-encoding: UTF-8

#日志
logging:
  file: log/logging
  level:
    src.main.java: info


# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mbyy0506
    driver-class-name: com.mysql.cj.jdbc.Driver
  #thymeleaf模板配置
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mvc:
    static-path-pattern: /**
  #freemarker模板配置
  freemarker:
    template-loader-path: classpath:/static/template/
    suffix: flt
    enabled: true
    cache: false
    charset: UTF-8
    content-type: text/html
    allow-request-override: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
  session:
    store-type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 0
    timeout: 30000s
  # kafka
  kafka:
    bootstrap-servers: 192.168.1.180:9092
    consumer:
      group-id: 0
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288

#zookeeper address
#zookeeper.address=192.168.1.180:2181

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#mtbatis配置  节点必须为独立的节点
mybatis:
  mapper-locations: classpath:/mapping/*Mapper.xml    #mapper映射xml文件的所有路径
  type-aliases-package: com.itstyle.seckill.pojo    #实体类中的路径

