package com.itstyle.seckill.pojo;

/*
* 外键类
* */
public class SuccessKilledKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.seckill_id
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    private Long seckillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.user_id
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.seckill_id
     *
     * @return the value of success_killed.seckill_id
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.seckill_id
     *
     * @param seckillId the value for success_killed.seckill_id
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.user_id
     *
     * @return the value of success_killed.user_id
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.user_id
     *
     * @param userId the value for success_killed.user_id
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}