package com.itstyle.seckill.pojo;

import java.io.Serializable;
import java.util.Date;

/*
* 秒杀成功类
*
* */
public class SuccessKilled extends SuccessKilledKey implements Serializable {

    private static final long serialVersionUID = -8323988269420485565L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.state
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.create_time
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.state
     *
     * @return the value of success_killed.state
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.state
     *
     * @param state the value for success_killed.state
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.create_time
     *
     * @return the value of success_killed.create_time
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.create_time
     *
     * @param createTime the value for success_killed.create_time
     *
     * @mbg.generated Sat Sep 29 11:03:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}